### ISSUE TITLE
Update Wolfenstein Enemy Territory Entity Definition file

### ISSUE THREAD

**Issue by Mateos81** [thunderpwn/ETL_gamepack#1]
See: https://github.com/TTimo/GtkRadiant/issues/379

I believe ETL has new entities (I don't know the current status of the AT-Gun?); I'd suggest to have them in a separated DEF file (i. e. etl_entities.def).

**Comment by thunderpwn** [comment]
allready invited you to join this repo @Mateos81 , you may upload anything you see fit..

**Comment by Mateos81** [comment]
Waiting for the validation on the Radiant side, and also details about if there are new entities in ETL... That's why I opened this issue.

**Comment by thunderpwn** [comment]
great, then we'll wait :) and please do check the rest of repo if I have done all the right way @Mateos81 as you know this one best
